#! /bin/bash
# *-* coding: iso8859-1 *-*

# script q pega os parametros $x da chamada e converte de iso-8859-1 
# para utf-8, renomeando o arquivo com um prefixo
for i in $*
do
	iconv -t UTF-8 -f ISO-8859-1 "$i" > "utf-$i"
done
