#!/usr/bin/env python
# *-* coding: iso8859-1 *-*

#Autor: Gustavo Serra Scalet

def resize(fp, nfp, q = 75):
	import PIL
	from PIL.JpegImagePlugin import JpegImageFile as jpeg

	image = PIL.Image.open(fp)
	jpeg.load(image)
	jpeg.save(image, nfp, quality=q)
	return 0

from sys import argv

# 1st argument is the filename, 
# 2st is the new filename and
# 3nd is the quality
try:
	fp = argv[1]
	nfp = argv[2]
except IndexError:
	print """Uso: %s <nome do arquivo> <novo nome do arquivo> [qualidade(0-100)]
A qualidade padrão é 75""" % argv[0]
	fp = ''
if fp:
	try:
		ret = resize(fp, nfp, int(argv[3]))
	except IndexError:
		ret = resize(fp, nfp)
	if ret == 0:
		print 'imagem %s compressada para %s com sucesso' % (fp, nfp)
